image: docker:git
services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
#  tags:
#    - docker
  only:
    - tags
